"""add has passed to user

Revision ID: 83295cbbb47d
Revises: f79aa63ebe0c
Create Date: 2026-08-18 19:24:14.519605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83295cbbb47d'
down_revision: Union[str, Sequence[str], None] = 'f79aa63ebe0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_passed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_passed')
    # ### end Alembic commands ###
