"""...

Revision ID: c494e4038e34
Revises: fd4179415643
Create Date: 2026-08-19 00:01:32.150527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c494e4038e34'
down_revision: Union[str, Sequence[str], None] = 'fd4179415643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('pickup_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('orders', 'pick_up_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('pick_up_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('orders', 'pickup_at')
    # ### end Alembic commands ###
