"""add is_admin to user

Revision ID: f79aa63ebe0c
Revises: 5d1c517d2c32
Create Date: 2026-08-18 15:49:48.057685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f79aa63ebe0c'
down_revision: Union[str, Sequence[str], None] = '5d1c517d2c32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_admin",
            sa.Boolean(),
            nullable=True,
        ),
    )

    op.execute(
        "UPDATE users SET is_admin = false WHERE is_admin IS NULL"
    )

    op.alter_column(
        "users",
        "is_admin",
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
