"""add delivery_address delivery_at pick_up_at

Revision ID: fd4179415643
Revises: 83295cbbb47d
Create Date: 2026-08-18 23:55:16.269130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd4179415643'
down_revision: Union[str, Sequence[str], None] = '83295cbbb47d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('pick_up_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('delivery_address', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('delivery_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_at')
    op.drop_column('orders', 'delivery_address')
    op.drop_column('orders', 'pick_up_at')
    # ### end Alembic commands ###
